# Generated by Django 2.2 on 2020-09-16 09:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50, verbose_name='User agent')),
                ('critical', models.CharField(max_length=50, verbose_name='criticality')),
                ('error', models.TextField()),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
                ('seen', models.BooleanField(default=False)),
                ('ticketed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Errors during payment request',
            },
        ),
    ]
