# Generated by Django 2.2 on 2020-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('credits', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Uwazii SMS Credit',
            },
        ),
    ]
