# Generated by Django 2.2 on 2020-09-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sent_Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('message_id', models.CharField(max_length=250, verbose_name='Message Id')),
            ],
            options={
                'verbose_name': 'Sent sms',
            },
        ),
        migrations.CreateModel(
            name='Starred_Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('error_code', models.CharField(max_length=50, verbose_name='Error code')),
                ('error_description', models.CharField(max_length=50, verbose_name='Error description')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobile Number')),
                ('message_id', models.CharField(max_length=50, verbose_name='Message_Id')),
                ('resent', models.BooleanField(default=False)),
                ('Time_resent', models.CharField(blank=True, max_length=50, verbose_name='Time resent')),
            ],
            options={
                'verbose_name': 'Starred sms',
            },
        ),
        migrations.CreateModel(
            name='Unsent_Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=250)),
                ('station', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('resent', models.BooleanField(default=False)),
                ('time_resent', models.CharField(blank=True, max_length=50, verbose_name='Time resent')),
            ],
            options={
                'verbose_name': 'Unsent sms',
            },
        ),
    ]
