# Generated by Django 2.2 on 2020-09-26 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_sent_sms_starred_sms_unsent_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='starred_sms',
            name='message',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unsent_sms',
            name='error',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
