# Generated by Django 2.2 on 2020-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClearOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemDate', models.DateTimeField()),
                ('Order_no', models.CharField(max_length=50, verbose_name='oder number')),
                ('Name', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=50)),
                ('Shipping_method', models.CharField(max_length=50, verbose_name='Shipping method')),
                ('Shipping_code', models.CharField(max_length=50, verbose_name='shipping code')),
                ('Date_placed', models.CharField(max_length=50, verbose_name='date_placed')),
                ('Status', models.CharField(max_length=50)),
                ('Signature', models.ImageField(upload_to='media/mobile/delivery/signatures')),
                ('Name_Other', models.CharField(blank=True, max_length=150, verbose_name='Name of secondary picker')),
                ('Phone_no', models.CharField(blank=True, max_length=50, verbose_name='secondary picker phone')),
                ('Relationship', models.CharField(blank=True, max_length=50, verbose_name='Relationship to the owner')),
            ],
            options={
                'verbose_name': 'Successful cleared orders',
            },
        ),
    ]
