# Generated by Django 2.2 on 2020-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMpesaTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_id', models.TextField(blank=True, verbose_name='merchant id')),
                ('checkout_request_id', models.TextField(blank=True, verbose_name='checkout request id')),
                ('Result_code', models.TextField(blank=True, verbose_name='Result code')),
                ('Result_description', models.TextField(blank=True, verbose_name='result description')),
            ],
            options={
                'verbose_name': 'All mpesa transaction',
                'verbose_name_plural': 'All Mpesa transactions',
            },
        ),
        migrations.CreateModel(
            name='MpesaCallBacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField()),
                ('caller', models.TextField(default='APP#1')),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call Back/dev',
                'verbose_name_plural': 'Mpesa Call Backs/dev',
            },
        ),
        migrations.CreateModel(
            name='MpesaCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.TextField(default='safaricom')),
                ('caller', models.TextField(default='APP#1')),
                ('conversation_id', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Mpesa Call/dev',
                'verbose_name_plural': 'Mpesa Calls/dev',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('transaction_time', models.TextField(blank='True', verbose_name='Transaction Time')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.TextField()),
                ('reference', models.TextField()),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone_number', models.TextField(verbose_name='phone number')),
                ('organization_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='balance')),
            ],
            options={
                'verbose_name': 'Mpesa Payment',
                'verbose_name_plural': 'Mpesa Payments',
            },
        ),
        migrations.CreateModel(
            name='SuccessfullMpesaPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.TextField(blank=True)),
                ('Receipt', models.TextField(blank=True)),
                ('Balance', models.TextField(blank=True)),
                ('TransactionDate', models.TextField(blank=True, verbose_name='transaction date')),
                ('PhoneNumber', models.TextField(blank=True, verbose_name='phone number')),
            ],
        ),
    ]
