# Generated by Django 2.2 on 2020-09-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuccessfullMpesaPayments',
            new_name='SuccessMpesaPayments',
        ),
    ]
