# Generated by Django 2.2 on 2020-09-11 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0003_auto_20200911_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='successmpesapayments',
            name='Result_code',
            field=models.TextField(blank=True, verbose_name='Result code'),
        ),
        migrations.AddField(
            model_name='successmpesapayments',
            name='Result_description',
            field=models.TextField(blank=True, verbose_name='result description'),
        ),
        migrations.AddField(
            model_name='successmpesapayments',
            name='SystemDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='System date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='successmpesapayments',
            name='checkout_request_id',
            field=models.TextField(blank=True, verbose_name='checkout request id'),
        ),
        migrations.AddField(
            model_name='successmpesapayments',
            name='merchant_id',
            field=models.TextField(blank=True, verbose_name='merchant id'),
        ),
    ]
