# Generated by Django 2.2 on 2020-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_auto_20200911_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successmpesapayments',
            name='Balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
