# Generated by Django 2.2 on 2020-09-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0005_auto_20200911_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='successmpesapayments',
            options={'verbose_name': 'Successful Mpesa transactions', 'verbose_name_plural': 'Successful Mpesa transactions'},
        ),
    ]
