# Generated by Django 2.2.14 on 2020-08-23 12:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=64)),
                ('Description', models.TextField(blank=True, verbose_name='What is the use of this carousel')),
                ('Title', models.CharField(blank=True, max_length=128)),
                ('Content', ckeditor.fields.RichTextField(blank=True)),
                ('Url', models.URLField(blank=True)),
                ('Button_Title', models.CharField(blank=True, max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='carousel/')),
            ],
            options={
                'verbose_name': 'Home page main carousel',
            },
        ),
        migrations.CreateModel(
            name='Home_Upper_DissapearingAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
                ('Button', models.CharField(max_length=50)),
                ('Link', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Advert that appears on top of carousel in home',
            },
        ),
        migrations.CreateModel(
            name='User_Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Phone', models.CharField(max_length=50)),
                ('Subject', models.CharField(blank=True, max_length=250)),
                ('Message', models.TextField()),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Resolved', models.BooleanField(default=False)),
                ('Notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'User queries from contact page',
            },
        ),
    ]
