# Generated by Django 2.2.14 on 2020-08-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200825_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselhome',
            name='Image',
        ),
    ]
