# Generated by Django 2.2.14 on 2020-08-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_carouselhome_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselhome',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pages/carousel/'),
        ),
    ]
