# Generated by Django 2.2.14 on 2020-08-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_carouselhome_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselHome',
            new_name='Carousel_Home',
        ),
    ]
