# Generated by Django 2.2.14 on 2020-08-26 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200825_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel_home',
            name='Image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='media/pages/carousel/'),
            preserve_default=False,
        ),
    ]
