# Generated by Django 2.2 on 2020-09-26 20:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200826_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_Home_mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=64)),
                ('Description', models.TextField(blank=True, verbose_name='What is the use of this carousel')),
                ('Title', models.CharField(blank=True, max_length=128)),
                ('Content', ckeditor.fields.RichTextField(blank=True)),
                ('Url', models.URLField(blank=True)),
                ('Button_Title', models.CharField(blank=True, max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='media/pages/mobile/carousel/')),
            ],
            options={
                'verbose_name': 'Home page main carousel',
            },
        ),
        migrations.DeleteModel(
            name='Home_Upper_DissapearingAdvert',
        ),
    ]
