# Generated by Django 2.2 on 2020-09-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200926_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel_home_mobile',
            options={'verbose_name': 'Home mobile main carousel'},
        ),
    ]
