# Generated by Django 2.2.14 on 2020-08-23 12:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Content', ckeditor.fields.RichTextField(verbose_name='Main content')),
                ('Secondary_Content', ckeditor.fields.RichTextField(verbose_name='Secondary content in the second column')),
                ('Tertial_Content', ckeditor.fields.RichTextField(verbose_name='Tertial content in the third column')),
            ],
            options={
                'verbose_name': 'Checkout footer',
            },
        ),
        migrations.CreateModel(
            name='External_Services_Bellow_Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=750, verbose_name='content bellow head')),
            ],
            options={
                'verbose_name': 'External services bellow head',
            },
        ),
        migrations.CreateModel(
            name='External_Services_Head_First_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=750, verbose_name='content first items in head')),
            ],
            options={
                'verbose_name': 'External services  head first item',
            },
        ),
        migrations.CreateModel(
            name='External_Services_Inner_Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Content', models.CharField(max_length=750, verbose_name='content inside  head')),
            ],
            options={
                'verbose_name': 'External services above head',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField(verbose_name='Descriptive content bellow the logo')),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50)),
                ('Quick_Links', ckeditor.fields.RichTextField(blank=True, verbose_name='Quick links eg contact us in a list form')),
                ('Legal', ckeditor.fields.RichTextField(blank=True, verbose_name='Legal links eg Privacy policy  in a list form')),
                ('Brand_One', models.ImageField(upload_to='media/base/footer')),
                ('Link_One', models.CharField(max_length=50)),
                ('Brand_Two', models.ImageField(upload_to='media/base/footer')),
                ('Link_Two', models.CharField(max_length=50)),
                ('Brand_Three', models.ImageField(upload_to='media/base/footer')),
                ('Link_Three', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Main Footer',
            },
        ),
        migrations.CreateModel(
            name='Footer_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twitter', models.CharField(blank=True, max_length=50, verbose_name='Twitter account link')),
                ('Pinterest', models.CharField(blank=True, max_length=50, verbose_name='Pintrest account link')),
                ('Facebook', models.CharField(blank=True, max_length=50, verbose_name='Facebook account link')),
                ('Youtube', models.CharField(blank=True, max_length=50, verbose_name='Youtube account link')),
                ('Instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram account link')),
            ],
            options={
                'verbose_name': 'Social media links at the footer',
            },
        ),
        migrations.CreateModel(
            name='Owl_Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Logo', models.ImageField(upload_to='media/base', verbose_name='image logo for partners size is 82x41')),
                ('Link', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Partner Logo',
                'verbose_name_plural': 'Partners Logos',
            },
        ),
        migrations.CreateModel(
            name='Product_Extra_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Product extra information',
            },
        ),
        migrations.CreateModel(
            name='Product_Shipping_And_Returns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Product shipping and returns',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'User Terms And Conditions',
            },
        ),
    ]
